//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::env::SnowballEnv;
use super::super::among::Among;

static A_0: &'static [Among<Context>; 2] = &[
    Among("gi", -1, 1, None),
    Among("ki", -1, 2, None),
];

static A_1: &'static [Among<Context>; 21] = &[
    Among("da", -1, 3, None),
    Among("mata", -1, 1, None),
    Among("b", -1, 3, None),
    Among("ksid", -1, 1, None),
    Among("nuksid", 3, 1, None),
    Among("me", -1, 3, None),
    Among("sime", 5, 1, None),
    Among("ksime", 6, 1, None),
    Among("nuksime", 7, 1, None),
    Among("akse", -1, 2, None),
    Among("dakse", 9, 1, None),
    Among("takse", 9, 1, None),
    Among("site", -1, 1, None),
    Among("ksite", 12, 1, None),
    Among("nuksite", 13, 1, None),
    Among("n", -1, 3, None),
    Among("sin", 15, 1, None),
    Among("ksin", 16, 1, None),
    Among("nuksin", 17, 1, None),
    Among("daks", -1, 1, None),
    Among("taks", -1, 1, None),
];

static A_2: &'static [Among<Context>; 9] = &[
    Among("aa", -1, -1, None),
    Among("ee", -1, -1, None),
    Among("ii", -1, -1, None),
    Among("oo", -1, -1, None),
    Among("uu", -1, -1, None),
    Among("\u{00E4}\u{00E4}", -1, -1, None),
    Among("\u{00F5}\u{00F5}", -1, -1, None),
    Among("\u{00F6}\u{00F6}", -1, -1, None),
    Among("\u{00FC}\u{00FC}", -1, -1, None),
];

static A_3: &'static [Among<Context>; 1] = &[
    Among("i", -1, 1, None),
];

static A_4: &'static [Among<Context>; 12] = &[
    Among("lane", -1, 1, None),
    Among("line", -1, 3, None),
    Among("mine", -1, 2, None),
    Among("lasse", -1, 1, None),
    Among("lisse", -1, 3, None),
    Among("misse", -1, 2, None),
    Among("lasi", -1, 1, None),
    Among("lisi", -1, 3, None),
    Among("misi", -1, 2, None),
    Among("last", -1, 1, None),
    Among("list", -1, 3, None),
    Among("mist", -1, 2, None),
];

static A_5: &'static [Among<Context>; 10] = &[
    Among("ga", -1, 1, None),
    Among("ta", -1, 1, None),
    Among("le", -1, 1, None),
    Among("sse", -1, 1, None),
    Among("l", -1, 1, None),
    Among("s", -1, 1, None),
    Among("ks", 5, 1, None),
    Among("t", -1, 2, None),
    Among("lt", 7, 1, None),
    Among("st", 7, 1, None),
];

static A_6: &'static [Among<Context>; 5] = &[
    Among("", -1, 2, None),
    Among("las", 0, 1, None),
    Among("lis", 0, 1, None),
    Among("mis", 0, 1, None),
    Among("t", 0, -1, None),
];

static A_7: &'static [Among<Context>; 7] = &[
    Among("d", -1, 4, None),
    Among("sid", 0, 2, None),
    Among("de", -1, 4, None),
    Among("ikkude", 2, 1, None),
    Among("ike", -1, 1, None),
    Among("ikke", -1, 1, None),
    Among("te", -1, 3, None),
];

static A_8: &'static [Among<Context>; 4] = &[
    Among("va", -1, -1, None),
    Among("du", -1, -1, None),
    Among("nu", -1, -1, None),
    Among("tu", -1, -1, None),
];

static A_9: &'static [Among<Context>; 3] = &[
    Among("kk", -1, 1, None),
    Among("pp", -1, 2, None),
    Among("tt", -1, 3, None),
];

static A_10: &'static [Among<Context>; 3] = &[
    Among("ma", -1, 2, None),
    Among("mai", -1, 1, None),
    Among("m", -1, 1, None),
];

static A_11: &'static [Among<Context>; 290] = &[
    Among("joob", -1, 1, None),
    Among("jood", -1, 1, None),
    Among("joodakse", 1, 1, None),
    Among("jooma", -1, 1, None),
    Among("joomata", 3, 1, None),
    Among("joome", -1, 1, None),
    Among("joon", -1, 1, None),
    Among("joote", -1, 1, None),
    Among("joovad", -1, 1, None),
    Among("juua", -1, 1, None),
    Among("juuakse", 9, 1, None),
    Among("j\u{00E4}i", -1, 12, None),
    Among("j\u{00E4}id", 11, 12, None),
    Among("j\u{00E4}ime", 11, 12, None),
    Among("j\u{00E4}in", 11, 12, None),
    Among("j\u{00E4}ite", 11, 12, None),
    Among("j\u{00E4}\u{00E4}b", -1, 12, None),
    Among("j\u{00E4}\u{00E4}d", -1, 12, None),
    Among("j\u{00E4}\u{00E4}da", 17, 12, None),
    Among("j\u{00E4}\u{00E4}dakse", 18, 12, None),
    Among("j\u{00E4}\u{00E4}di", 17, 12, None),
    Among("j\u{00E4}\u{00E4}ks", -1, 12, None),
    Among("j\u{00E4}\u{00E4}ksid", 21, 12, None),
    Among("j\u{00E4}\u{00E4}ksime", 21, 12, None),
    Among("j\u{00E4}\u{00E4}ksin", 21, 12, None),
    Among("j\u{00E4}\u{00E4}ksite", 21, 12, None),
    Among("j\u{00E4}\u{00E4}ma", -1, 12, None),
    Among("j\u{00E4}\u{00E4}mata", 26, 12, None),
    Among("j\u{00E4}\u{00E4}me", -1, 12, None),
    Among("j\u{00E4}\u{00E4}n", -1, 12, None),
    Among("j\u{00E4}\u{00E4}te", -1, 12, None),
    Among("j\u{00E4}\u{00E4}vad", -1, 12, None),
    Among("j\u{00F5}i", -1, 1, None),
    Among("j\u{00F5}id", 32, 1, None),
    Among("j\u{00F5}ime", 32, 1, None),
    Among("j\u{00F5}in", 32, 1, None),
    Among("j\u{00F5}ite", 32, 1, None),
    Among("keeb", -1, 4, None),
    Among("keed", -1, 4, None),
    Among("keedakse", 38, 4, None),
    Among("keeks", -1, 4, None),
    Among("keeksid", 40, 4, None),
    Among("keeksime", 40, 4, None),
    Among("keeksin", 40, 4, None),
    Among("keeksite", 40, 4, None),
    Among("keema", -1, 4, None),
    Among("keemata", 45, 4, None),
    Among("keeme", -1, 4, None),
    Among("keen", -1, 4, None),
    Among("kees", -1, 4, None),
    Among("keeta", -1, 4, None),
    Among("keete", -1, 4, None),
    Among("keevad", -1, 4, None),
    Among("k\u{00E4}ia", -1, 8, None),
    Among("k\u{00E4}iakse", 53, 8, None),
    Among("k\u{00E4}ib", -1, 8, None),
    Among("k\u{00E4}id", -1, 8, None),
    Among("k\u{00E4}idi", 56, 8, None),
    Among("k\u{00E4}iks", -1, 8, None),
    Among("k\u{00E4}iksid", 58, 8, None),
    Among("k\u{00E4}iksime", 58, 8, None),
    Among("k\u{00E4}iksin", 58, 8, None),
    Among("k\u{00E4}iksite", 58, 8, None),
    Among("k\u{00E4}ima", -1, 8, None),
    Among("k\u{00E4}imata", 63, 8, None),
    Among("k\u{00E4}ime", -1, 8, None),
    Among("k\u{00E4}in", -1, 8, None),
    Among("k\u{00E4}is", -1, 8, None),
    Among("k\u{00E4}ite", -1, 8, None),
    Among("k\u{00E4}ivad", -1, 8, None),
    Among("laob", -1, 16, None),
    Among("laod", -1, 16, None),
    Among("laoks", -1, 16, None),
    Among("laoksid", 72, 16, None),
    Among("laoksime", 72, 16, None),
    Among("laoksin", 72, 16, None),
    Among("laoksite", 72, 16, None),
    Among("laome", -1, 16, None),
    Among("laon", -1, 16, None),
    Among("laote", -1, 16, None),
    Among("laovad", -1, 16, None),
    Among("loeb", -1, 14, None),
    Among("loed", -1, 14, None),
    Among("loeks", -1, 14, None),
    Among("loeksid", 83, 14, None),
    Among("loeksime", 83, 14, None),
    Among("loeksin", 83, 14, None),
    Among("loeksite", 83, 14, None),
    Among("loeme", -1, 14, None),
    Among("loen", -1, 14, None),
    Among("loete", -1, 14, None),
    Among("loevad", -1, 14, None),
    Among("loob", -1, 7, None),
    Among("lood", -1, 7, None),
    Among("loodi", 93, 7, None),
    Among("looks", -1, 7, None),
    Among("looksid", 95, 7, None),
    Among("looksime", 95, 7, None),
    Among("looksin", 95, 7, None),
    Among("looksite", 95, 7, None),
    Among("looma", -1, 7, None),
    Among("loomata", 100, 7, None),
    Among("loome", -1, 7, None),
    Among("loon", -1, 7, None),
    Among("loote", -1, 7, None),
    Among("loovad", -1, 7, None),
    Among("luua", -1, 7, None),
    Among("luuakse", 106, 7, None),
    Among("l\u{00F5}i", -1, 6, None),
    Among("l\u{00F5}id", 108, 6, None),
    Among("l\u{00F5}ime", 108, 6, None),
    Among("l\u{00F5}in", 108, 6, None),
    Among("l\u{00F5}ite", 108, 6, None),
    Among("l\u{00F6}\u{00F6}b", -1, 5, None),
    Among("l\u{00F6}\u{00F6}d", -1, 5, None),
    Among("l\u{00F6}\u{00F6}dakse", 114, 5, None),
    Among("l\u{00F6}\u{00F6}di", 114, 5, None),
    Among("l\u{00F6}\u{00F6}ks", -1, 5, None),
    Among("l\u{00F6}\u{00F6}ksid", 117, 5, None),
    Among("l\u{00F6}\u{00F6}ksime", 117, 5, None),
    Among("l\u{00F6}\u{00F6}ksin", 117, 5, None),
    Among("l\u{00F6}\u{00F6}ksite", 117, 5, None),
    Among("l\u{00F6}\u{00F6}ma", -1, 5, None),
    Among("l\u{00F6}\u{00F6}mata", 122, 5, None),
    Among("l\u{00F6}\u{00F6}me", -1, 5, None),
    Among("l\u{00F6}\u{00F6}n", -1, 5, None),
    Among("l\u{00F6}\u{00F6}te", -1, 5, None),
    Among("l\u{00F6}\u{00F6}vad", -1, 5, None),
    Among("l\u{00FC}\u{00FC}a", -1, 5, None),
    Among("l\u{00FC}\u{00FC}akse", 128, 5, None),
    Among("m\u{00FC}\u{00FC}a", -1, 13, None),
    Among("m\u{00FC}\u{00FC}akse", 130, 13, None),
    Among("m\u{00FC}\u{00FC}b", -1, 13, None),
    Among("m\u{00FC}\u{00FC}d", -1, 13, None),
    Among("m\u{00FC}\u{00FC}di", 133, 13, None),
    Among("m\u{00FC}\u{00FC}ks", -1, 13, None),
    Among("m\u{00FC}\u{00FC}ksid", 135, 13, None),
    Among("m\u{00FC}\u{00FC}ksime", 135, 13, None),
    Among("m\u{00FC}\u{00FC}ksin", 135, 13, None),
    Among("m\u{00FC}\u{00FC}ksite", 135, 13, None),
    Among("m\u{00FC}\u{00FC}ma", -1, 13, None),
    Among("m\u{00FC}\u{00FC}mata", 140, 13, None),
    Among("m\u{00FC}\u{00FC}me", -1, 13, None),
    Among("m\u{00FC}\u{00FC}n", -1, 13, None),
    Among("m\u{00FC}\u{00FC}s", -1, 13, None),
    Among("m\u{00FC}\u{00FC}te", -1, 13, None),
    Among("m\u{00FC}\u{00FC}vad", -1, 13, None),
    Among("n\u{00E4}eb", -1, 18, None),
    Among("n\u{00E4}ed", -1, 18, None),
    Among("n\u{00E4}eks", -1, 18, None),
    Among("n\u{00E4}eksid", 149, 18, None),
    Among("n\u{00E4}eksime", 149, 18, None),
    Among("n\u{00E4}eksin", 149, 18, None),
    Among("n\u{00E4}eksite", 149, 18, None),
    Among("n\u{00E4}eme", -1, 18, None),
    Among("n\u{00E4}en", -1, 18, None),
    Among("n\u{00E4}ete", -1, 18, None),
    Among("n\u{00E4}evad", -1, 18, None),
    Among("n\u{00E4}gema", -1, 18, None),
    Among("n\u{00E4}gemata", 158, 18, None),
    Among("n\u{00E4}ha", -1, 18, None),
    Among("n\u{00E4}hakse", 160, 18, None),
    Among("n\u{00E4}hti", -1, 18, None),
    Among("p\u{00F5}eb", -1, 15, None),
    Among("p\u{00F5}ed", -1, 15, None),
    Among("p\u{00F5}eks", -1, 15, None),
    Among("p\u{00F5}eksid", 165, 15, None),
    Among("p\u{00F5}eksime", 165, 15, None),
    Among("p\u{00F5}eksin", 165, 15, None),
    Among("p\u{00F5}eksite", 165, 15, None),
    Among("p\u{00F5}eme", -1, 15, None),
    Among("p\u{00F5}en", -1, 15, None),
    Among("p\u{00F5}ete", -1, 15, None),
    Among("p\u{00F5}evad", -1, 15, None),
    Among("saab", -1, 2, None),
    Among("saad", -1, 2, None),
    Among("saada", 175, 2, None),
    Among("saadakse", 176, 2, None),
    Among("saadi", 175, 2, None),
    Among("saaks", -1, 2, None),
    Among("saaksid", 179, 2, None),
    Among("saaksime", 179, 2, None),
    Among("saaksin", 179, 2, None),
    Among("saaksite", 179, 2, None),
    Among("saama", -1, 2, None),
    Among("saamata", 184, 2, None),
    Among("saame", -1, 2, None),
    Among("saan", -1, 2, None),
    Among("saate", -1, 2, None),
    Among("saavad", -1, 2, None),
    Among("sai", -1, 2, None),
    Among("said", 190, 2, None),
    Among("saime", 190, 2, None),
    Among("sain", 190, 2, None),
    Among("saite", 190, 2, None),
    Among("s\u{00F5}i", -1, 9, None),
    Among("s\u{00F5}id", 195, 9, None),
    Among("s\u{00F5}ime", 195, 9, None),
    Among("s\u{00F5}in", 195, 9, None),
    Among("s\u{00F5}ite", 195, 9, None),
    Among("s\u{00F6}\u{00F6}b", -1, 9, None),
    Among("s\u{00F6}\u{00F6}d", -1, 9, None),
    Among("s\u{00F6}\u{00F6}dakse", 201, 9, None),
    Among("s\u{00F6}\u{00F6}di", 201, 9, None),
    Among("s\u{00F6}\u{00F6}ks", -1, 9, None),
    Among("s\u{00F6}\u{00F6}ksid", 204, 9, None),
    Among("s\u{00F6}\u{00F6}ksime", 204, 9, None),
    Among("s\u{00F6}\u{00F6}ksin", 204, 9, None),
    Among("s\u{00F6}\u{00F6}ksite", 204, 9, None),
    Among("s\u{00F6}\u{00F6}ma", -1, 9, None),
    Among("s\u{00F6}\u{00F6}mata", 209, 9, None),
    Among("s\u{00F6}\u{00F6}me", -1, 9, None),
    Among("s\u{00F6}\u{00F6}n", -1, 9, None),
    Among("s\u{00F6}\u{00F6}te", -1, 9, None),
    Among("s\u{00F6}\u{00F6}vad", -1, 9, None),
    Among("s\u{00FC}\u{00FC}a", -1, 9, None),
    Among("s\u{00FC}\u{00FC}akse", 215, 9, None),
    Among("teeb", -1, 17, None),
    Among("teed", -1, 17, None),
    Among("teeks", -1, 17, None),
    Among("teeksid", 219, 17, None),
    Among("teeksime", 219, 17, None),
    Among("teeksin", 219, 17, None),
    Among("teeksite", 219, 17, None),
    Among("teeme", -1, 17, None),
    Among("teen", -1, 17, None),
    Among("teete", -1, 17, None),
    Among("teevad", -1, 17, None),
    Among("tegema", -1, 17, None),
    Among("tegemata", 228, 17, None),
    Among("teha", -1, 17, None),
    Among("tehakse", 230, 17, None),
    Among("tehti", -1, 17, None),
    Among("toob", -1, 10, None),
    Among("tood", -1, 10, None),
    Among("toodi", 234, 10, None),
    Among("tooks", -1, 10, None),
    Among("tooksid", 236, 10, None),
    Among("tooksime", 236, 10, None),
    Among("tooksin", 236, 10, None),
    Among("tooksite", 236, 10, None),
    Among("tooma", -1, 10, None),
    Among("toomata", 241, 10, None),
    Among("toome", -1, 10, None),
    Among("toon", -1, 10, None),
    Among("toote", -1, 10, None),
    Among("toovad", -1, 10, None),
    Among("tuua", -1, 10, None),
    Among("tuuakse", 247, 10, None),
    Among("t\u{00F5}i", -1, 10, None),
    Among("t\u{00F5}id", 249, 10, None),
    Among("t\u{00F5}ime", 249, 10, None),
    Among("t\u{00F5}in", 249, 10, None),
    Among("t\u{00F5}ite", 249, 10, None),
    Among("viia", -1, 3, None),
    Among("viiakse", 254, 3, None),
    Among("viib", -1, 3, None),
    Among("viid", -1, 3, None),
    Among("viidi", 257, 3, None),
    Among("viiks", -1, 3, None),
    Among("viiksid", 259, 3, None),
    Among("viiksime", 259, 3, None),
    Among("viiksin", 259, 3, None),
    Among("viiksite", 259, 3, None),
    Among("viima", -1, 3, None),
    Among("viimata", 264, 3, None),
    Among("viime", -1, 3, None),
    Among("viin", -1, 3, None),
    Among("viisime", -1, 3, None),
    Among("viisin", -1, 3, None),
    Among("viisite", -1, 3, None),
    Among("viite", -1, 3, None),
    Among("viivad", -1, 3, None),
    Among("v\u{00F5}ib", -1, 11, None),
    Among("v\u{00F5}id", -1, 11, None),
    Among("v\u{00F5}ida", 274, 11, None),
    Among("v\u{00F5}idakse", 275, 11, None),
    Among("v\u{00F5}idi", 274, 11, None),
    Among("v\u{00F5}iks", -1, 11, None),
    Among("v\u{00F5}iksid", 278, 11, None),
    Among("v\u{00F5}iksime", 278, 11, None),
    Among("v\u{00F5}iksin", 278, 11, None),
    Among("v\u{00F5}iksite", 278, 11, None),
    Among("v\u{00F5}ima", -1, 11, None),
    Among("v\u{00F5}imata", 283, 11, None),
    Among("v\u{00F5}ime", -1, 11, None),
    Among("v\u{00F5}in", -1, 11, None),
    Among("v\u{00F5}is", -1, 11, None),
    Among("v\u{00F5}ite", -1, 11, None),
    Among("v\u{00F5}ivad", -1, 11, None),
];

static G_V1: &'static [u8; 20] = &[17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 48, 8];

static G_RV: &'static [u8; 3] = &[17, 65, 16];

static G_KI: &'static [u8; 36] = &[117, 66, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 16];

static G_GI: &'static [u8; 20] = &[21, 123, 243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 48, 8];

#[derive(Clone)]
struct Context {
    i_p1: i32,
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_p1 = env.limit;
    'golab0: loop {
        let v_1 = env.cursor;
        'lab1: loop {
            if !env.in_grouping(G_V1, 97, 252) {
                break 'lab1;
            }
            env.cursor = v_1;
            break 'golab0;
        }
        env.cursor = v_1;
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    'golab2: loop {
        'lab3: loop {
            if !env.out_grouping(G_V1, 97, 252) {
                break 'lab3;
            }
            break 'golab2;
        }
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    context.i_p1 = env.cursor;
    return true
}

fn r_emphasis(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_0, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    let v_3 = env.limit - env.cursor;
    if !env.hop_back(4) {
        return false;
    }
    env.cursor = env.limit - v_3;
    match among_var {
        1 => {
            let v_4 = env.limit - env.cursor;
            if !env.in_grouping_b(G_GI, 97, 252) {
                return false;
            }
            env.cursor = env.limit - v_4;
            let v_5 = env.limit - env.cursor;
            'lab0: loop {
                if !r_LONGV(env, context) {
                    break 'lab0;
                }
                return false;
            }
            env.cursor = env.limit - v_5;
            if !env.slice_del() {
                return false;
            }
        }
        2 => {
            if !env.in_grouping_b(G_KI, 98, 382) {
                return false;
            }
            if !env.slice_del() {
                return false;
            }
        }
        _ => ()
    }
    return true
}

fn r_verb(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_1, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            if !env.slice_del() {
                return false;
            }
        }
        2 => {
            if !env.slice_from("a") {
                return false;
            }
        }
        3 => {
            if !env.in_grouping_b(G_V1, 97, 252) {
                return false;
            }
            if !env.slice_del() {
                return false;
            }
        }
        _ => ()
    }
    return true
}

fn r_LONGV(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.find_among_b(A_2, context) == 0 {
        return false;
    }
    return true
}

fn r_i_plural(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    if env.find_among_b(A_3, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    if !env.in_grouping_b(G_RV, 97, 117) {
        return false;
    }
    if !env.slice_del() {
        return false;
    }
    return true
}

fn r_special_noun_endings(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_4, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            if !env.slice_from("lase") {
                return false;
            }
        }
        2 => {
            if !env.slice_from("mise") {
                return false;
            }
        }
        3 => {
            if !env.slice_from("lise") {
                return false;
            }
        }
        _ => ()
    }
    return true
}

fn r_case_ending(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_5, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            'lab0: loop {
                let v_3 = env.limit - env.cursor;
                'lab1: loop {
                    if !env.in_grouping_b(G_RV, 97, 117) {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_3;
                if !r_LONGV(env, context) {
                    return false;
                }
                break 'lab0;
            }
        }
        2 => {
            let v_4 = env.limit - env.cursor;
            if !env.hop_back(4) {
                return false;
            }
            env.cursor = env.limit - v_4;
        }
        _ => ()
    }
    if !env.slice_del() {
        return false;
    }
    return true
}

fn r_plural_three_first_cases(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_7, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            if !env.slice_from("iku") {
                return false;
            }
        }
        2 => {
            let v_3 = env.limit - env.cursor;
            'lab0: loop {
                if !r_LONGV(env, context) {
                    break 'lab0;
                }
                return false;
            }
            env.cursor = env.limit - v_3;
            if !env.slice_del() {
                return false;
            }
        }
        3 => {
            'lab1: loop {
                let v_4 = env.limit - env.cursor;
                'lab2: loop {
                    let v_5 = env.limit - env.cursor;
                    if !env.hop_back(4) {
                        break 'lab2;
                    }
                    env.cursor = env.limit - v_5;
                    among_var = env.find_among_b(A_6, context);
                    match among_var {
                        1 => {
                            if !env.slice_from("e") {
                                return false;
                            }
                        }
                        2 => {
                            if !env.slice_del() {
                                return false;
                            }
                        }
                        _ => ()
                    }
                    break 'lab1;
                }
                env.cursor = env.limit - v_4;
                if !env.slice_from("t") {
                    return false;
                }
                break 'lab1;
            }
        }
        4 => {
            'lab3: loop {
                let v_6 = env.limit - env.cursor;
                'lab4: loop {
                    if !env.in_grouping_b(G_RV, 97, 117) {
                        break 'lab4;
                    }
                    break 'lab3;
                }
                env.cursor = env.limit - v_6;
                if !r_LONGV(env, context) {
                    return false;
                }
                break 'lab3;
            }
            if !env.slice_del() {
                return false;
            }
        }
        _ => ()
    }
    return true
}

fn r_nu(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    if env.find_among_b(A_8, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    if !env.slice_del() {
        return false;
    }
    return true
}

fn r_undouble_kpt(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if !env.in_grouping_b(G_V1, 97, 252) {
        return false;
    }
    if context.i_p1 > env.cursor{
        return false;
    }
    env.ket = env.cursor;
    among_var = env.find_among_b(A_9, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !env.slice_from("k") {
                return false;
            }
        }
        2 => {
            if !env.slice_from("p") {
                return false;
            }
        }
        3 => {
            if !env.slice_from("t") {
                return false;
            }
        }
        _ => ()
    }
    return true
}

fn r_degrees(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_10, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            if !env.in_grouping_b(G_RV, 97, 117) {
                return false;
            }
            if !env.slice_del() {
                return false;
            }
        }
        2 => {
            if !env.slice_del() {
                return false;
            }
        }
        _ => ()
    }
    return true
}

fn r_substantive(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let v_1 = env.limit - env.cursor;
    r_special_noun_endings(env, context);
    env.cursor = env.limit - v_1;
    let v_2 = env.limit - env.cursor;
    r_case_ending(env, context);
    env.cursor = env.limit - v_2;
    let v_3 = env.limit - env.cursor;
    r_plural_three_first_cases(env, context);
    env.cursor = env.limit - v_3;
    let v_4 = env.limit - env.cursor;
    r_degrees(env, context);
    env.cursor = env.limit - v_4;
    let v_5 = env.limit - env.cursor;
    r_i_plural(env, context);
    env.cursor = env.limit - v_5;
    let v_6 = env.limit - env.cursor;
    r_nu(env, context);
    env.cursor = env.limit - v_6;
    return true
}

fn r_verb_exceptions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.bra = env.cursor;
    among_var = env.find_among(A_11, context);
    if among_var == 0 {
        return false;
    }
    env.ket = env.cursor;
    if env.cursor < env.limit {
        return false;
    }
    match among_var {
        1 => {
            if !env.slice_from("joo") {
                return false;
            }
        }
        2 => {
            if !env.slice_from("saa") {
                return false;
            }
        }
        3 => {
            if !env.slice_from("viima") {
                return false;
            }
        }
        4 => {
            if !env.slice_from("keesi") {
                return false;
            }
        }
        5 => {
            if !env.slice_from("l\u{00F6}\u{00F6}") {
                return false;
            }
        }
        6 => {
            if !env.slice_from("l\u{00F5}i") {
                return false;
            }
        }
        7 => {
            if !env.slice_from("loo") {
                return false;
            }
        }
        8 => {
            if !env.slice_from("k\u{00E4}isi") {
                return false;
            }
        }
        9 => {
            if !env.slice_from("s\u{00F6}\u{00F6}") {
                return false;
            }
        }
        10 => {
            if !env.slice_from("too") {
                return false;
            }
        }
        11 => {
            if !env.slice_from("v\u{00F5}isi") {
                return false;
            }
        }
        12 => {
            if !env.slice_from("j\u{00E4}\u{00E4}ma") {
                return false;
            }
        }
        13 => {
            if !env.slice_from("m\u{00FC}\u{00FC}si") {
                return false;
            }
        }
        14 => {
            if !env.slice_from("luge") {
                return false;
            }
        }
        15 => {
            if !env.slice_from("p\u{00F5}de") {
                return false;
            }
        }
        16 => {
            if !env.slice_from("ladu") {
                return false;
            }
        }
        17 => {
            if !env.slice_from("tegi") {
                return false;
            }
        }
        18 => {
            if !env.slice_from("n\u{00E4}gi") {
                return false;
            }
        }
        _ => ()
    }
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_p1: 0,
    };
    let v_1 = env.cursor;
    'lab0: loop {
        if !r_verb_exceptions(env, context) {
            break 'lab0;
        }
        return false;
    }
    env.cursor = v_1;
    let v_2 = env.cursor;
    r_mark_regions(env, context);
    env.cursor = v_2;
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_3 = env.limit - env.cursor;
    r_emphasis(env, context);
    env.cursor = env.limit - v_3;
    let v_4 = env.limit - env.cursor;
    'lab1: loop {
        'lab2: loop {
            let v_5 = env.limit - env.cursor;
            'lab3: loop {
                if !r_verb(env, context) {
                    break 'lab3;
                }
                break 'lab2;
            }
            env.cursor = env.limit - v_5;
            r_substantive(env, context);
            break 'lab2;
        }
        break 'lab1;
    }
    env.cursor = env.limit - v_4;
    let v_6 = env.limit - env.cursor;
    r_undouble_kpt(env, context);
    env.cursor = env.limit - v_6;
    env.cursor = env.limit_backward;
    return true
}
