
name: Publish a release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release tantivy-stemmers to Crates.io
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust toolchain [stable]
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build tantivy-stemmers
      run: cargo build

    - name: Publish tantivy-stemmers
      run: cargo publish --token ${CRATES_API_TOKEN}
      env:
        CRATES_API_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
